### ISSUE TITLE
 0.1.2 and 0.1.3 are breaking changes

### ISSUE THREAD

**Issue by ghuserchris** [arenanet/uppity#2]
Versions 0.1.2 and 0.1.3 should have been set at least 1.0.0 because there are breaking changes, specifically this: 
`  "engines": {
    "node": ">=14.15.4"
  }`
yarn install sees this and exits with error if lower versions are used.  Please delete these releases: 0.1.2 and 0.1.3

**Comment by kevinkace** [comment]
Thanks for filling this issue. I've deleted the 0.1.2 and 0.1.3 releases in GH, and published v1.0.0 to npm.
